name: Publish

on:
  release:
    types:
      - published

jobs:
  release:
    name: Create & Publish Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: |
          zip -r forbidden-lands.zip assets fonts lang templates forbidden-lands.js forbidden-lands.css system.json template.json CHANGELOG.md CONTRIBUTING.md LICENSE README.md
      - name: Update Release with Artifacts
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          artifacts: './forbidden-lands.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
  foundry:
    name: Push to Foundry
    runs-on: ubuntu-latest
    steps:
      - name: Get Version Number
        id: tag
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "::set-output name=version::${TAG_NAME//v/}"
      - name: Push to Foundry
        id: foundry
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://foundryvtt.com/_api/packages/release_version/'
          customHeaders: '{ "Content-Type": "application/json", "Authorization": "${{ secrets.FOUNDRY_TOKEN }}" }'
          data:
            '{
              "id": "forbidden-lands",
              "release": {
                "version": "${{ steps.tag.outputs.version }}",
                "manifest": "https://raw.githubusercontent.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/${{ github.event.release.tag_name }}/system.json",
                "notes": "https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/releases/tag/${{ github.event.release.tag_name }}",
                "compatibility": {
                  "minimum": "13",
                  "verified": "13.348",
                  "maximum": "13"
                }
              }
            }'
      - name: Summary
        run: |
          echo "**Version:** ${{ steps.tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Release Notes:** ${{ github.event.release.html_url }}" >> $GITHUB_STEP_SUMMARY
          echo "**Published:** ${{ steps.foundry.outputs.response }}" >> $GITHUB_STEP_SUMMARY
